### ISSUE TITLE
Multiple declaration of Transproc::Transformer causes duplication

### ISSUE THREAD

**Issue by Kukunin** [solnic/transproc#95]
I'm not sure this is something we should fix, but I've spent 3 hours on it. If one file is included multiple times, it appends transformations.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required.'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'transproc'
  gem 'rspec'
  gem 'pry'
end

require 'rspec/autorun'

describe Transproc::Transformer do
  let(:container) do
    Module.new do
      extend Transproc::Registry

      def self.arbitrary(value, fn)
        fn[value]
      end
    end
  end

  let(:transformer) { Transproc::Transformer[container] }
  after { Object.send(:remove_const, :A) }

  def declare_A
    eval <<~CLASS
      class A < transformer
        arbitrary ->(v) { v + 1 }
      end
    CLASS
  end

  it 'does not affect the final transproc' do
    2.times { declare_A }

    expect(A.build.call(1)).to eq 2
  end
end
```

```
Failures:

  1) Transproc::Transformer inheritance with double declaration does not affect the final transproc
     Failure/Error: expect(A.build.call(1)).to eq 2
     
       expected: 2
            got: 3
     
       (compared using ==)
     # ./spec/unit/transformer_spec.rb:75:in `block (4 levels) in <top (required)>'
```

This is because of class instance `@transformations`
